database_url: "postgres://postgres:postgres@localhost:5432/keeper?sslmode=disable"
cert_file: "./keys/server.crt"
key_file: "./keys/server.key"
key: "s5as4d5a#$%#%s6ad545##$%#4353KSFjH"
query_timeout: 2s
ws:
  address: "localhost:4443"